<?php

/**
 * Implements hook_theme().
 */
function addthis_theme() {
  return array(
    'addthis_wrapper' => array(
      'render element' => 'element',
    ),
    'addthis_element' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * @TODO Find another way to do this since it breaks aggregation.
 * @param array $page
 */
function addthis_page_attachments(array &$page){
  $page['#attached']['library'][] = 'addthis/addthis.global';


// Include the widget js when we include on all but admin pages.
  //if (!path_is_admin(current_path()) && AddThis::getInstance()->getWidgetJsInclude() == AddThis::WIDGET_JS_INCLUDE_PAGE) {
  $manager = \Drupal\addthis\Services\AddThisScriptManager::getInstance();
  $manager->attachJsToElement($page);
  //}

}


function addthis_library_info_alter(){

}


/**
 * Implementation to retrieve formatters for a given type of field.
 */
function _addthis_field_info_formatter_field_type($field_type = NULL) {
  $formatters = \Drupal::Service('plugin.manager.field.formatter')->getDefinitions();
  foreach ($formatters as $key => $formatter) {
    if (!in_array((!isset($field_type) ? 'addthis' : $field_type), $formatter['field_types'])) {
      unset($formatters[$key]);
    }
  }
  return $formatters;
}


