<?php

/**
 * Implements hook_theme().
 */
function addthis_theme() {
  return [
    'addthis_wrapper' => [
      'render element' => 'element',
    ],
    'addthis_element' => [
      'render element' => 'element',
    ],
    'addthis_basic_button' => [
      'render element' => 'element',
    ],
    'addthis_basic_toolbox' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implementation to retrieve formatters for a given type of field.
 */
function _addthis_field_info_formatter_field_type($field_type = NULL) {
  $formatters = \Drupal::Service('plugin.manager.field.formatter')
    ->getDefinitions();
  foreach ($formatters as $key => $formatter) {
    if (!in_array((!isset($field_type) ? 'addthis' : $field_type), $formatter['field_types'])) {
      unset($formatters[$key]);
    }
  }
  return $formatters;
}


